version: "3.8"

services:
  app:
    build: ./dockerfiles
    working_dir: /home/app
    ports:
      - "3000:3000"
      - "9005:9005"
    volumes:
      - ./:/home/app
    tty: true
    stdin_open: true
    command: yarn dev
